In [101]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl

In [102]:
# df =  pd.read_csv('house_price_dataset.csv')
# df.head()

In [103]:
# model evalution metric(R squared)
# Train Test Split
# Training accuracy vs Testing Accuracy
# Prediction Program using all above

In [104]:
# label encoding

In [105]:
temp_df = pd.DataFrame(
    {'Spicy':['Hot', 'Medium', 'Low','Hot','Low', 'Medium']}
) #Ordinal
temp_df

    Spicy
0     Hot
1  Medium
2     Low
3     Hot
4     Low
5  Medium

In [106]:
from sklearn.preprocessing import LabelEncoder

In [107]:
label_encoder = LabelEncoder()

In [108]:
label_encoder.fit_transform(temp_df['Spicy'])

array([0, 2, 1, 0, 1, 2])

In [109]:
temp_df['Spicy'].map({'Hot':2, 'Medium':1, 'Low':0})

0    2
1    1
2    0
3    2
4    0
5    1
Name: Spicy, dtype: int64

In [110]:
# one-hot encoding

In [111]:
temp_df

    Spicy
0     Hot
1  Medium
2     Low
3     Hot
4     Low
5  Medium

In [112]:
pd.get_dummies(temp_df,prefix='spicy_level')

   spicy_level_Hot  spicy_level_Low  spicy_level_Medium
0             True            False               False
1            False            False                True
2            False             True               False
3             True            False               False
4            False             True               False
5            False            False                True

In [113]:
# 1. Create dataset

df =  pd.read_csv('house_price_dataset.csv')
df.head()

   size_aana  size_ropani       location  floors  house_age_years    price_npr
0       5.30        0.331  New Baneshwor     2.0                7   23385000.0
1       8.01        0.501       Chabahil     2.5                7   32212000.0
2      48.48        3.030      Baneshwor     1.0               29  168630000.0
3       2.13        0.133        Gongabu     1.0               24    6507000.0
4       2.84        0.177       Chabahil     2.0               27   14041000.0

In [114]:
one_hot_encoded_df = pd.get_dummies(df)

In [115]:
one_hot_encoded_df

,size_aana,size_ropani,floors,house_age_years,price_npr,location_Baluwatar,location_Baneshwor,location_Bhaktapur,location_Boudha,location_Budhanilkantha,...,location_Gongabu,location_Jhamsikhel,location_Kalanki,location_Kalimati,location_Kirtipur,location_Koteshwor,location_Lazimpat,location_Naxal,location_New Baneshwor,location_Sanepa
0,5.30,0.331,2.0,7,23385000.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,8.01,0.501,2.5,7,32212000.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,48.48,3.030,1.0,29,168630000.0,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,2.13,0.133,1.0,24,6507000.0,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,2.84,0.177,2.0,27,14041000.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,6.27,0.392,2.5,24,20680000.0,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
1196,9.59,0.599,2.5,13,40951000.0,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1197,13.97,0.873,2.0,2,78582000.0,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1198,16.50,1.031,0.0,19,40805000.0,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1199,2.18,0.136,2.0,26,11192000.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [116]:
# create a model
# Fit/Train a model
# Prediction

In [117]:
# 2. Separate features and target
y =  one_hot_encoded_df['price_npr']

In [118]:
del(one_hot_encoded_df['price_npr'] )

In [119]:
X = one_hot_encoded_df

In [120]:
X

,size_aana,size_ropani,floors,house_age_years,location_Baluwatar,location_Baneshwor,location_Bhaktapur,location_Boudha,location_Budhanilkantha,location_Chabahil,location_Gongabu,location_Jhamsikhel,location_Kalanki,location_Kalimati,location_Kirtipur,location_Koteshwor,location_Lazimpat,location_Naxal,location_New Baneshwor,location_Sanepa
0,5.30,0.331,2.0,7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,8.01,0.501,2.5,7,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
2,48.48,3.030,1.0,29,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,2.13,0.133,1.0,24,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
4,2.84,0.177,2.0,27,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,6.27,0.392,2.5,24,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1196,9.59,0.599,2.5,13,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1197,13.97,0.873,2.0,2,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
1198,16.50,1.031,0.0,19,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
1199,2.18,0.136,2.0,26,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False

In [121]:
df.head()

   size_aana  size_ropani       location  floors  house_age_years    price_npr
0       5.30        0.331  New Baneshwor     2.0                7   23385000.0
1       8.01        0.501       Chabahil     2.5                7   32212000.0
2      48.48        3.030      Baneshwor     1.0               29  168630000.0
3       2.13        0.133        Gongabu     1.0               24    6507000.0
4       2.84        0.177       Chabahil     2.0               27   14041000.0

In [122]:
from sklearn.linear_model import LinearRegression

In [123]:
df['location'].unique()

<StringArray>
[ 'New Baneshwor',       'Chabahil',      'Baneshwor',        'Gongabu',
         'Sanepa',     'Jhamsikhel', 'Budhanilkantha',       'Kalimati',
          'Naxal',       'Kirtipur',      'Koteshwor',        'Kalanki',
      'Baluwatar',       'Lazimpat',         'Boudha',      'Bhaktapur']
Length: 16, dtype: str

In [124]:
linear_regression_model = LinearRegression()

In [125]:
# model.fit(input, output)
linear_regression_model.fit(X, y)

LinearRegression()

In [126]:
X.columns

Index(['size_aana', 'size_ropani', 'floors', 'house_age_years',
       'location_Baluwatar', 'location_Baneshwor', 'location_Bhaktapur',
       'location_Boudha', 'location_Budhanilkantha', 'location_Chabahil',
       'location_Gongabu', 'location_Jhamsikhel', 'location_Kalanki',
       'location_Kalimati', 'location_Kirtipur', 'location_Koteshwor',
       'location_Lazimpat', 'location_Naxal', 'location_New Baneshwor',
       'location_Sanepa'],
      dtype='str')

In [127]:
X.head()

,size_aana,size_ropani,floors,house_age_years,location_Baluwatar,location_Baneshwor,location_Bhaktapur,location_Boudha,location_Budhanilkantha,location_Chabahil,location_Gongabu,location_Jhamsikhel,location_Kalanki,location_Kalimati,location_Kirtipur,location_Koteshwor,location_Lazimpat,location_Naxal,location_New Baneshwor,location_Sanepa
0,5.30,0.331,2.0,7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,8.01,0.501,2.5,7,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
2,48.48,3.030,1.0,29,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,2.13,0.133,1.0,24,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
4,2.84,0.177,2.0,27,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False

In [128]:
# predicting price for location Bhaktapur so in place of Bhaktapur keeping 1 and rest 0
linear_regression_model.predict([[4,0,2,3,5,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0]])[0]

C:\Users\Hemraj\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

np.float64(804247349.1003718)

In [129]:
from sklearn.model_selection import train_test_split

In [130]:
# 3. Train-test split
X_TRAIN, X_TEST, y_train, y_test = train_test_split(X,y)

In [131]:
X.shape

(1200, 20)

In [132]:
X_TRAIN.shape

(900, 20)

In [133]:
y_train.shape

(900,)

In [134]:
X_TEST.shape

(300, 20)

In [135]:
y_test.shape

(300,)

In [145]:
# 4. Create model
train_test_split_model = LinearRegression()

# 5. Train model
train_test_split_model.fit(X_TRAIN,y_train)

LinearRegression()

In [137]:
X_TRAIN.head()

,size_aana,size_ropani,floors,house_age_years,location_Baluwatar,location_Baneshwor,location_Bhaktapur,location_Boudha,location_Budhanilkantha,location_Chabahil,location_Gongabu,location_Jhamsikhel,location_Kalanki,location_Kalimati,location_Kirtipur,location_Koteshwor,location_Lazimpat,location_Naxal,location_New Baneshwor,location_Sanepa
810,8.09,0.506,1.0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
460,7.64,0.477,2.0,28,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
279,16.54,1.034,3.0,17,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
596,28.80,1.800,1.0,8,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
63,2.26,0.141,0.0,13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [146]:
# 6. Predict test data
train_test_split_model.predict(X_TEST)

array([ 1.74171881e+08,  6.32967834e+07,  5.75814247e+07,  3.00598383e+07,
        7.02371757e+07,  2.67828409e+07,  1.53563505e+08,  1.10490983e+07,
        6.65319482e+07,  1.60400308e+08,  3.24085427e+07,  2.22580864e+07,
        5.86245536e+07,  2.37824616e+07,  1.32903285e+07, -5.24389793e+06,
        2.74047807e+07,  4.77487576e+07,  2.82854659e+07,  6.60453555e+06,
        1.38111516e+06,  1.71159103e+07,  7.98749754e+07,  1.59763467e+07,
        4.90257488e+07,  9.03299618e+07,  4.79807661e+07,  2.30161886e+07,
        8.68163028e+07,  1.64161958e+07,  2.00731827e+08,  5.80854089e+07,
        8.72918801e+06,  1.98254139e+07,  7.23913458e+07,  5.93463795e+07,
        6.89053000e+07, -2.11585652e+06,  8.54346667e+07, -1.61587607e+05,
        5.07932333e+07,  8.36691774e+07,  3.28774142e+07,  4.51044671e+07,
        7.78117437e+07,  3.33416818e+07, -4.35398261e+05, -1.49174254e+07,
        4.68054680e+07,  9.82403014e+07,  6.96595523e+07,  4.76782107e+07,
        1.37928631e+07,  7.19829520e+07,  9.15280965e+07,  4.88786255e+07,
        1.55323561e+08,  8.39289655e+07,  1.01399234e+08, -1.08166372e+07,
        7.83036390e+07,  2.62789236e+05, -6.74286540e+06,  4.16687714e+07,
       -1.68372743e+07,  4.81575951e+07,  2.89425701e+07,  7.50170215e+07,
        3.03175714e+07,  2.33079977e+08,  1.60358545e+08,  7.15591166e+07,
        8.81485325e+07,  5.59400319e+07,  2.08440853e+05,  4.62222502e+07,
        4.41128843e+07,  1.46804012e+07,  8.26129261e+07,  7.62726082e+07,
        3.28183797e+07,  2.00846414e+07,  1.61362210e+08, -1.05553949e+07,
        5.20825499e+07,  3.73480138e+07,  2.39538200e+07,  1.32757501e+08,
        2.94527943e+07,  2.17980281e+07,  1.71074817e+07, -2.15959744e+07,
        3.14456148e+07,  1.69315028e+06,  9.05139675e+07,  9.01813648e+07,
        2.57562203e+06,  1.11286536e+08,  2.18391412e+07,  8.67963665e+07,
        3.20373553e+06, -4.80401914e+06,  4.13628580e+07,  5.35501034e+07,
        2.57500933e+07,  6.50197474e+07,  3.47969149e+07,  5.49235091e+06,
        9.18726604e+07,  8.23103792e+07,  7.38626775e+06,  8.68800707e+06,
        6.23403796e+07,  2.94927651e+07,  4.64153346e+07,  8.03776293e+06,
        1.12866811e+07,  5.56436667e+07,  3.99320130e+07,  4.85020849e+07,
        3.54887006e+07,  5.81424162e+06,  5.79762235e+06,  3.22728401e+07,
        5.17328300e+07,  2.25943621e+07,  5.48316676e+05,  3.83749421e+07,
        6.09272600e+07,  3.14976985e+07,  5.85017714e+07,  7.24445550e+07,
        5.77728955e+07,  5.29383455e+07,  6.63604964e+06,  2.49196666e+07,
        4.85026276e+07,  8.14636341e+06,  7.51816653e+07,  1.69235203e+07,
        2.83042156e+07,  2.94958337e+07,  8.67189984e+07,  4.16168032e+07,
        1.77096139e+07,  1.57385974e+07,  1.20966002e+08,  9.01630644e+07,
        8.26009687e+07,  7.51204310e+07,  6.61562117e+07,  6.40638591e+07,
        6.64839342e+07,  2.07143337e+08,  8.93510213e+07,  2.06206697e+07,
        8.97338623e+07,  6.62467082e+07,  5.79550348e+07,  5.98067511e+07,
        2.78187837e+07,  3.11132198e+07,  5.27328297e+07,  1.38050321e+07,
        8.32888964e+07,  6.41372537e+07,  8.57174118e+07,  5.17095398e+07,
        5.29483403e+07,  6.57869620e+07,  3.66115743e+07,  2.02944112e+08,
        3.38330164e+07,  2.90892227e+07,  3.42754943e+06,  4.61795700e+07,
       -1.13852828e+07,  6.87425338e+07, -5.03520109e+05,  3.14996766e+07,
        3.09005467e+07,  6.11872112e+07,  1.62764991e+08,  4.98794469e+07,
        2.01371200e+05,  5.50830252e+07,  5.26562447e+07,  9.13625760e+07,
        2.49857904e+07,  7.65050050e+07,  1.02347727e+08,  4.06647618e+07,
        2.29039343e+07,  8.71358689e+07,  1.57862729e+08,  5.53332517e+07,
        8.48532194e+07,  4.25830589e+07,  6.59978009e+07,  3.87555071e+07,
        5.30127057e+07,  8.98050636e+07,  3.59250627e+07,  8.08990440e+07,
        6.12780420e+07,  4.13284386e+07,  5.59921885e+07,  6.46127005e+07,
        1.76556986e+08,  1.17289873e+08,  9.02419097e+07,  7.83821118e+06,
        2.94114245e+07,  6.82727522e+07,  6.29546124e+07,  5.87889551e+07,
        3.72551247e+07,  2.80010956e+07,  7.48143712e+07,  9.50695794e+06,
        6.21978244e+07,  4.26444500e+07,  1.98560876e+08,  1.56958896e+07,
        8.44386915e+07,  3.94936501e+07, -1.23215751e+06,  5.29151763e+07,
        1.32365999e+07,  1.93026150e+08,  9.82445553e+07,  1.92494306e+08,
        4.54257371e+06,  8.71652265e+07,  1.32045507e+08,  3.36202924e+07,
        6.58255750e+07,  7.00782965e+07,  8.72784821e+07, -1.21148280e+06,
        8.57663437e+07,  7.40604394e+07,  5.56813707e+07,  6.43554536e+07,
        8.62687940e+07,  1.76436918e+06,  2.44462491e+07,  4.28085700e+07,
        9.45970824e+07,  8.04988981e+07,  1.16957783e+08,  8.38887618e+07,
        2.64552459e+07,  6.30364657e+07,  5.29254248e+07, -2.11478434e+06,
        3.40620504e+07,  8.35645981e+07,  9.23370493e+07,  2.18265470e+07,
        3.56936451e+07,  6.05828442e+07,  4.39146131e+06,  5.52481539e+07,
        2.16157910e+07,  2.30315442e+07,  5.10155007e+07,  5.79487880e+07,
        6.49049363e+07,  5.26716679e+07,  5.26491947e+07,  9.41611725e+07,
        7.15352171e+07,  2.59991227e+07,  6.24353891e+07,  5.46260878e+07,
       -1.02878885e+07,  7.68050448e+07,  1.55464935e+07,  5.99777002e+07,
        3.71339615e+07,  5.91421800e+07, -2.40604299e+05,  3.32735812e+07,
        1.38866907e+08,  7.36838384e+07,  2.23093037e+08,  2.78677470e+07,
        2.80965713e+07,  5.77541642e+07,  9.97966176e+07,  2.97632776e+07,
        3.92703948e+05,  8.02793760e+07,  3.36909263e+06,  2.03159784e+08,
        5.41899499e+07,  7.06941773e+07,  4.78850958e+07,  4.19483646e+07])

In [139]:
X_TEST.head()

,size_aana,size_ropani,floors,house_age_years,location_Baluwatar,location_Baneshwor,location_Bhaktapur,location_Boudha,location_Budhanilkantha,location_Chabahil,location_Gongabu,location_Jhamsikhel,location_Kalanki,location_Kalimati,location_Kirtipur,location_Koteshwor,location_Lazimpat,location_Naxal,location_New Baneshwor,location_Sanepa
81,50.72,3.170,3.0,11,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
831,7.95,0.497,2.5,15,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
130,14.80,0.925,2.0,19,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
829,2.13,0.133,0.0,2,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
132,12.69,0.793,1.0,5,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False

In [140]:
train_test_split_model.coef_

array([ 1.35869293e+08, -2.11460206e+09,  2.17844525e+06, -3.81162398e+05,
        3.78935207e+07,  6.31707314e+05, -3.15571817e+07, -9.47877352e+06,
       -2.11489774e+07, -4.82838693e+06, -1.69829807e+07,  1.76863673e+07,
       -1.34841561e+07, -9.75971631e+06, -2.46744824e+07, -9.75600653e+06,
        2.93881723e+07,  3.67670128e+07, -1.64775802e+06,  2.09516393e+07])

In [141]:
train_test_split_model.intercept_

np.float64(4976274.718233667)

In [142]:
y_train_prediction = train_test_split_model.predict(X_TRAIN)

In [143]:
from sklearn.metrics import r2_score

In [144]:
r2_score(y_train, y_train_prediction)

0.8853195425381025