In [ ]:
# House Rent Prediction Using Deep Learning

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("kathmandu_rent.csv")
df.head(10)

   area_sqft  bedrooms  distance_km  parking  monthly_rent_npr
0        388         1         13.4        1              5000
1       1449         3          8.9        1             22700
2       1264         3          2.2        1             23800
3        930         2          0.5        0             16400
4        921         2          7.7        0             10000
5       1580         3         14.3        0             17000
6        383         1          8.8        1              8700
7       1330         3          5.9        1             23900
8        562         1          0.9        1             16000
9        395         1         13.8        0              5000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   area_sqft         5000 non-null   int64
 1   bedrooms          5000 non-null   int64
 2   distance_km       5000 non-null   float64
 3   parking           5000 non-null   int64
 4   monthly_rent_npr  5000 non-null   int64
dtypes: float64(1), int64(4)
memory usage: 195.4 KB

In [5]:
X = df[["area_sqft","bedrooms","distance_km","parking"]]
Y = df["monthly_rent_npr"]

In [6]:
X.head(2)

   area_sqft  bedrooms  distance_km  parking
0        388         1         13.4        1
1       1449         3          8.9        1

In [7]:
Y.head(2)

0     5000
1    22700
Name: monthly_rent_npr, dtype: int64

In [8]:
# scaling

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [9]:
X

array([[0.08908974, 0.        , 0.88965517, 1.        ],
       [0.77404777, 0.5       , 0.57931034, 1.        ],
       [0.65461588, 0.5       , 0.11724138, 1.        ],
       ...,
       [0.8198838 , 0.5       , 0.73793103, 1.        ],
       [0.67850226, 0.5       , 0.33793103, 1.        ],
       [0.49838606, 0.5       , 0.73103448, 0.        ]], shape=(5000, 4))

In [10]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [11]:
# # scaling

# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)
# X_train[:3]

In [12]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Input, Dense

model = Sequential([
    Input(shape=(4,)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1),
])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │             160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 705 (2.75 KB)

 Trainable params: 705 (2.75 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
from tensorflow.keras.optimizers import Adam,SGD

model.compile(
    optimizer=SGD(learning_rate=0.5), 
    loss='mse'
             )

In [14]:
history = model.fit(X_train, Y_train, epochs=100, verbose=1)
print("Loss at start:", round(history.history['loss'][0], 2))

Epoch 1/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: nan
Epoch 2/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 3/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 4/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 5/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 6/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 7/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 8/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 9/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 10/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 11/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 12/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 13/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 14/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 15/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 16/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 17/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 18/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 19/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 20/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 21/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 22/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 23/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 24/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 25/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 26/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 27/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 28/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 29/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 30/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 31/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 32/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 33/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 34/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 35/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 36/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 37/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 38/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 39/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 40/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 41/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 42/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 43/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 44/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 45/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 46/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 47/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 48/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 49/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 50/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 51/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 52/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 53/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 54/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 55/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 56/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 57/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 58/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 59/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 60/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 61/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 62/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 63/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 64/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 65/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 66/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 67/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 68/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 69/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 70/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 71/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 72/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 73/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 74/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 75/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 76/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 77/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 78/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 79/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 80/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 81/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 82/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 83/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 84/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 85/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 86/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 87/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 88/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 89/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 90/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 91/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 92/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 93/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 94/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 95/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 96/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 97/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Epoch 98/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 99/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: nan
Epoch 100/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: nan
Loss at start: nan